### ISSUE TITLE
I'm having a hard time to get all env vars [Question]

### ISSUE THREAD

**Issue by some81** [JuzouSatoru2/NextJs-Website#2]
Hi there,

I'm trying to set up the project but I'm having a hard time getting all env variables.
Can you please provide an example.env file? 
Thanks

**Comment by some81** [comment]
Actually my bad I saw you have a template.env, but it still looks like it doesn't contain all available vars

**Comment by JuzouSatoru2** [comment]
Hi,
You can look up all environment variables in the documentation [here](https://github.com/JuzouSatoru2/NextJs-Website/blob/master/docs/EnvVariables.md).
