### ISSUE TITLE
[Bug] Why the /admin not working

### ISSUE THREAD

**Issue by some81** [JuzouSatoru2/NextJs-Website#4]
When try to access /admin I get 404

**Comment by JuzouSatoru2** [comment]
The admin route is protected. You have to login on the /login route. Ypu have to set the password in your .env file.

**Comment by some81** [comment]
Usually when you have restricted access to something you should get 403 instead of 404.

**Comment by JuzouSatoru2** [comment]
I know. This is on purpose.
